### ISSUE TITLE
Python porting

### ISSUE THREAD

**Issue by ondrej1024** [benceszasz/CareLinkJavaClient#1]
Hi @benceszasz 

I am trying to port this CareLinkJavaClient to Python. The idea is to run it with microPython on an embedded device.

I have the first 3 steps of the authorization procedure working but I cannot get the AUTH_TOKEN. If I understand things correctly it should be provided by the server as a cookie. But I am not sure during what step of the authorization procedure it is sent as I am not seeing it. 

These are the cookies I get after each step:

`getLoginSession()`
* no cookies

`doLogin()`
* sessionCookie
* ssoCookie

`doConsent()`
* no cookies

Each step seems to be successful as I get a 200 response from the CareLink server for each of them. Looking at your code the AUTH_TOKEN should be available after that. Do I miss something?

**Comment by ondrej1024** [comment]
Never mind, I sorted it out. Login is working now.

**Comment by MJS0007** [comment]
Would you happen to have a copy of the working python script you could share?

**Comment by ondrej1024** [comment]
Of course. You can find it in the repo:
https://github.com/ondrej1024/carelink-python-client

**Comment by MJS0007** [comment]
Excellent, thank you!... I just need to figure out how to make it work with the Carelink>Nightscout connector now
